Fix test failures for `NoMethodError`
```
Failure/Error:
  expect { tanshuku_url.shortened_url }.to raise_error(
    NoMethodError,
    "undefined method `merge' for nil:NilClass"
  )

  expected NoMethodError with "undefined method `merge' for nil:NilClass", got #<NoMethodError: undefined method `merge' for nil> with backtrace:
    # ./app/models/tanshuku/url.rb:176:in `shortened_url'
    # ./spec/models/tanshuku/url_spec.rb:1131:in `block (6 levels) in <top (required)>'
    # ./spec/models/tanshuku/url_spec.rb:1131:in `block (5 levels) in <top (required)>'
# ./spec/models/tanshuku/url_spec.rb:1131:in `block (5 levels) in <top (required)>'
```

Ruby 3.3 doesn’t show inspected object on `NoMethodError`.